version: 2
updates:
# Maintain dependencies for Go.
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 10
# Maintain dependencies for GitHub Actions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 10
